### ISSUE TITLE
Hbase not in Zookeeper

### ISSUE THREAD

**Issue by rnwolf** [zsiciarz/vagrant-hbase#10]
I've setup Vagrant VM as follows

git clone https://github.com/zsiciarz/vagrant-hbase.git && cd vagrant-hbase && vagrant up
vagrant provision
vagrant ssh

Then I try to create the test table and I get an error.

Any suggestions?

```
vagrant@vagrant-hbase:~$ cd hbase/
vagrant@vagrant-hbase:~/hbase$ ./bin/hbase shell /vagrant/data/create_test_table.rb 
2015-03-26 22:18:29,491 WARN  [main] util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2015-03-26 22:18:30,327 ERROR [main] client.ConnectionManager$HConnectionImplementation: The node /hbase is not in ZooKeeper. It should have been written by the master. Check the value configured in 'zookeeper.znode.parent'. There could be a mismatch with the one configured in the master.
2015-03-26 22:18:30,529 ERROR [main] client.ConnectionManager$HConnectionImplementation: The node /hbase is not in ZooKeeper. It should have been written by the master. Check the value configured in 'zookeeper.znode.parent'. There could be a mismatch with the one configured in the master.
2015-03-26 22:18:30,832 ERROR [main] client.ConnectionManager$HConnectionImplementation: The node /hbase is not in ZooKeeper. It should have been written by the master. Check the value configured in 'zookeeper.znode.parent'. There could be a mismatch with the one configured in the master.
2015-03-26 22:18:31,333 ERROR [main] client.ConnectionManager$HConnectionImplementation: The node /hbase is not in ZooKeeper. It should have been written by the master. Check the value configured in 'zookeeper.znode.parent'. There could be a mismatch with the one configured in the master.
2015-03-26 22:18:32,338 ERROR [main] client.ConnectionManager$HConnectionImplementation: The node /hbase is not in ZooKeeper. It should have been written by the master. Check the value configured in 'zookeeper.znode.parent'. There could be a mismatch with the one configured in the master.
2015-03-26 22:18:34,352 ERROR [main] client.ConnectionManager$HConnectionImplementation: The node /hbase is not in ZooKeeper. It should have been written by the master. Check the value configured in 'zookeeper.znode.parent'. There could be a mismatch with the one configured in the master.
2015-03-26 22:18:38,388 ERROR [main] client.ConnectionManager$HConnectionImplementation: The node /hbase is not in ZooKeeper. It should have been written by the master. Check the value configured in 'zookeeper.znode.parent'. There could be a mismatch with the one configured in the master.

ERROR: The node /hbase is not in ZooKeeper. It should have been written by the master. Check the value configured in 'zookeeper.znode.parent'. There could be a mismatch with the one configured in the master.

```

**Comment by hooperbloob** [comment]
I'm seeing the same problem, it seems that HBase isn't starting correctly owing to a configuration issue.  From the hbase-vagrant-master-vagrant-hbase.log:

2015-04-04 01:02:45,729 INFO  [main] util.ServerCommandLine: env:HBASE_THRIFT_OPTS=
2015-04-04 01:02:45,732 INFO  [main] util.ServerCommandLine: env:PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
2015-04-04 01:02:45,732 INFO  [main] util.ServerCommandLine: env:USER=vagrant
2015-04-04 01:02:45,732 INFO  [main] util.ServerCommandLine: env:HBASE_SECURITY_LOGGER=INFO,RFAS
2015-04-04 01:02:45,733 INFO  [main] util.ServerCommandLine: env:HOME=/home/vagrant
2015-04-04 01:02:45,733 INFO  [main] util.ServerCommandLine: env:HBASE_START_FILE=/tmp/hbase-vagrant-master.autorestart
2015-04-04 01:02:45,733 INFO  [main] util.ServerCommandLine: env:XDG_SESSION_ID=4
2015-04-04 01:02:45,733 INFO  [main] util.ServerCommandLine: env:HBASE_LOGFILE=hbase-vagrant-master-vagrant-hbase.log
2015-04-04 01:02:45,733 INFO  [main] util.ServerCommandLine: env:XDG_RUNTIME_DIR=/run/user/1000
2015-04-04 01:02:45,733 INFO  [main] util.ServerCommandLine: env:LANG=C
2015-04-04 01:02:45,733 INFO  [main] util.ServerCommandLine: env:HBASE_LOG_PREFIX=hbase-vagrant-master-vagrant-hbase
2015-04-04 01:02:45,733 INFO  [main] util.ServerCommandLine: env:HBASE_IDENT_STRING=vagrant
2015-04-04 01:02:45,743 INFO  [main] util.ServerCommandLine: vmName=Java HotSpot(TM) 64-Bit Server VM, vmVendor=Oracle Corporation, vmVersion=24.76-b04
2015-04-04 01:02:45,749 INFO  [main] util.ServerCommandLine: vmInputArguments=[-Dproc_master, -XX:OnOutOfMemoryError=kill -9 %p, -XX:+UseConcMarkSweepGC, -Dhbase.log.dir=/home/vagrant/hbase-1.0.0/bin/../logs, -Dhbase.log.file=hbase-vagrant-master-vagrant-hbase.log, -Dhbase.home.dir=/home/vagrant/hbase-1.0.0/bin/.., -Dhbase.id.str=vagrant, -Dhbase.root.logger=INFO,RFA, -Dhbase.security.logger=INFO,RFAS]
2015-04-04 01:02:48,062 FATAL [main] regionserver.RSRpcServices: The hostname of regionserver cannot be set to localhost in a fully-distributed setup because it won't be reachable. See "Getting Started" for more information.
2015-04-04 01:02:48,063 ERROR [main] master.HMasterCommandLine: Master exiting
java.lang.RuntimeException: Failed construction of Master: class org.apache.hadoop.hbase.master.HMaster
        at org.apache.hadoop.hbase.master.HMaster.constructMaster(HMaster.java:1982)
        at org.apache.hadoop.hbase.master.HMasterCommandLine.startMaster(HMasterCommandLine.java:198)
        at org.apache.hadoop.hbase.master.HMasterCommandLine.run(HMasterCommandLine.java:139)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
        at org.apache.hadoop.hbase.util.ServerCommandLine.doMain(ServerCommandLine.java:126)
        at org.apache.hadoop.hbase.master.HMaster.main(HMaster.java:1996)
Caused by: java.io.IOException: The hostname of regionserver cannot be set to localhost in a fully-distributed setup because it won't be reachable. See "Getting Started" for more information.
        at org.apache.hadoop.hbase.regionserver.RSRpcServices.<init>(RSRpcServices.java:775)
        at org.apache.hadoop.hbase.master.MasterRpcServices.<init>(MasterRpcServices.java:195)
        at org.apache.hadoop.hbase.master.HMaster.createRpcServices(HMaster.java:474)
        at org.apache.hadoop.hbase.regionserver.HRegionServer.<init>(HRegionServer.java:492)
        at org.apache.hadoop.hbase.master.HMaster.<init>(HMaster.java:333)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

**Comment by hooperbloob** [comment]
One person's fork uses an alternate hadoop & hbase source:

https://github.com/ohamada/vagrant-hbase/commit/a1b3de880bb7320ffdaac94ecf011f49172b39f6

This (later version?) fixes the IOException above but no we're still left with issue mentioned at the top:

The node /hbase is not in ZooKeeper.   Per comments on StackOverflow, the hbase-site.xml
was modified to point to /hbase-unsecure instead:

 <property>
        <name>zookeeper.znode.parent</name>
        <value>/hbase-unsecure</value>
    </property>

This merely caused the same original error but now specifying /hbase-unsecure   So, stymied at
this point....
